"""add dob and self_intro field for a Dummy

Revision ID: a8768738aab3
Revises: a93046a1a3a2
Create Date: 2026-04-08 13:12:14.258487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8768738aab3'
down_revision: Union[str, Sequence[str], None] = 'a93046a1a3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('google_oauth_credentials_app_user_id_idx'), table_name='google_oauth_credentials')
    op.drop_table('google_oauth_credentials')
    op.drop_index(op.f('google_oauth_states_app_user_id_idx'), table_name='google_oauth_states')
    op.drop_index(op.f('google_oauth_states_state_idx'), table_name='google_oauth_states')
    op.drop_table('google_oauth_states')
    op.add_column('dummies', sa.Column('dob', sa.String(length=10), nullable=True))
    op.add_column('dummies', sa.Column('self_intro', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dummies', 'self_intro')
    op.drop_column('dummies', 'dob')
    op.create_table('google_oauth_states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), nullable=False),
    sa.Column('app_user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('code_verifier', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('google_oauth_states_pkey'))
    )
    op.create_index(op.f('google_oauth_states_state_idx'), 'google_oauth_states', ['state'], unique=1)
    op.create_index(op.f('google_oauth_states_app_user_id_idx'), 'google_oauth_states', ['app_user_id'], unique=False)
    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('token_uri', sa.VARCHAR(length=255), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('client_secret', sa.VARCHAR(length=255), nullable=True),
    sa.Column('scopes', sa.TEXT(), nullable=False),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('google_oauth_credentials_pkey'))
    )
    op.create_index(op.f('google_oauth_credentials_app_user_id_idx'), 'google_oauth_credentials', ['app_user_id'], unique=1)
    # ### end Alembic commands ###
