"""fix column

Revision ID: 3ed53db3b1f7
Revises: e33be3375258
Create Date: 2026-04-29 15:44:43.551275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed53db3b1f7'
down_revision: Union[str, Sequence[str], None] = 'e33be3375258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('google_oauth_credentials_pkey'))
    )
    op.create_index(op.f('google_oauth_credentials_app_user_id_idx'), 'google_oauth_credentials', ['app_user_id'], unique=True)
    op.create_table('google_oauth_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('app_user_id', sa.String(length=255), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('google_oauth_states_pkey'))
    )
    op.create_index(op.f('google_oauth_states_app_user_id_idx'), 'google_oauth_states', ['app_user_id'], unique=False)
    op.create_index(op.f('google_oauth_states_state_idx'), 'google_oauth_states', ['state'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('google_oauth_states_state_idx'), table_name='google_oauth_states')
    op.drop_index(op.f('google_oauth_states_app_user_id_idx'), table_name='google_oauth_states')
    op.drop_table('google_oauth_states')
    op.drop_index(op.f('google_oauth_credentials_app_user_id_idx'), table_name='google_oauth_credentials')
    op.drop_table('google_oauth_credentials')
    # ### end Alembic commands ###
