"""remove dummy table

Revision ID: 5093b00cea81
Revises: e95bc0011d68
Create Date: 2026-04-17 18:41:04.161062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5093b00cea81'
down_revision: Union[str, Sequence[str], None] = 'e95bc0011d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('dummies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dob', sa.VARCHAR(length=10), nullable=True),
    sa.Column('self_intro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), server_default=sa.text("'add_password_plz'"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dummies_pkey'))
    )
    op.create_table('orders',
    sa.Column('order_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_cancel', sa.BOOLEAN(), nullable=True),
    sa.Column('office_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('private_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('treatment_selected', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('order_number', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###
