"""add_role_column_and_missing_models

Revision ID: fb433e7d7823
Revises: 76a5be52d85f
Create Date: 2026-04-14 16:17:07.166738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb433e7d7823'
down_revision: Union[str, Sequence[str], None] = '76a5be52d85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.Column('office_email', sa.String(length=255), nullable=True),
    sa.Column('private_email', sa.String(length=255), nullable=True),
    sa.Column('treatment_selected', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('order_number', name=op.f('orders_pkey'))
    )
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('orders')
    # ### end Alembic commands ###
