"""create orders table

Revision ID: f545786d436b
Revises: 3ed53db3b1f7
Create Date: 2026-04-30 18:16:12.710748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f545786d436b'
down_revision: Union[str, Sequence[str], None] = '3ed53db3b1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_cancel', sa.Boolean(), nullable=True),
    sa.Column('office_email', sa.String(length=255), nullable=True),
    sa.Column('private_email', sa.String(length=255), nullable=True),
    sa.Column('treatment_selected', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('order_number', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('orders_merchant_id_idx'), 'orders', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('orders_merchant_id_idx'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
