"""add google oauth state auth_url

Revision ID: f205227fcace
Revises: ab31512d58b8
Create Date: 2026-05-04 14:42:53.797741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f205227fcace'
down_revision: Union[str, Sequence[str], None] = 'ab31512d58b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "google_oauth_states",
        sa.Column(
            "auth_url",
            sa.Text(),
            nullable=False,
            server_default="",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_oauth_states', 'auth_url')
    # ### end Alembic commands ###
