"""add dummies password

Revision ID: 8f22b57b6de3
Revises: a8768738aab3
Create Date: 2026-04-09 12:47:22.794461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8f22b57b6de3"
down_revision: Union[str, Sequence[str], None] = "a8768738aab3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dummies",
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            server_default="add_password_plz",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dummies", "password_hash")
    # ### end Alembic commands ###
